-- MySQL Script generated by MySQL Workbench
-- Sun Apr  1 15:20:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema communitydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema communitydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `communitydb` DEFAULT CHARACTER SET utf8 ;
USE `communitydb` ;

-- -----------------------------------------------------
-- Table `communitydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `communitydb`.`user` (
  `wechat_id` VARCHAR(16) NOT NULL,
  `name` VARCHAR(32) NULL,
  `phone` INT NULL,
  `sex` INT NULL COMMENT '0为男生，1为女生\n',
  `grade` INT NULL,
  `major` VARCHAR(32) NULL,
  PRIMARY KEY (`wechat_id`));


-- -----------------------------------------------------
-- Table `communitydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `communitydb`.`message` (
  `message_id` VARCHAR(45) NOT NULL,
  `content` VARCHAR(256) NOT NULL,
  `user_wechat_id` VARCHAR(16) NOT NULL,
  `readed` TINYINT NOT NULL DEFAULT 0,
  `sendtime` DATE NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `fk_message_user_idx` (`user_wechat_id` ASC),
  CONSTRAINT `fk_message_user`
    FOREIGN KEY (`user_wechat_id`)
    REFERENCES `communitydb`.`user` (`wechat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `communitydb`.`community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `communitydb`.`community` (
  `com_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`com_id`, `name`),
  UNIQUE INDEX `community_id_UNIQUE` (`com_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `communitydb`.`community_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `communitydb`.`community_has_user` (
  `community_com_id` VARCHAR(45) NOT NULL,
  `user_wechat_id` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`community_com_id`, `user_wechat_id`),
  INDEX `fk_community_has_user_user1_idx` (`user_wechat_id` ASC),
  INDEX `fk_community_has_user_community1_idx` (`community_com_id` ASC),
  CONSTRAINT `fk_community_has_user_community1`
    FOREIGN KEY (`community_com_id`)
    REFERENCES `communitydb`.`community` (`com_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_community_has_user_user1`
    FOREIGN KEY (`user_wechat_id`)
    REFERENCES `communitydb`.`user` (`wechat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
